apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claim
  annotations:
    konghq.com/strip-path: 'true'
    #konghq.com/plugins: 'add-header-route'
spec:
  ingressClassName: kong
  rules:
    - host: da.com 
      http:
        paths:
          - path: /claim
            pathType: ImplementationSpecific
            backend:
              service:
                name: echo
                port:
                  number: 80
