deployment:
  userDefinedVolumes:
    - name: custom-plugins
      hostPath:
        path: /kong/plugins

  userDefinedVolumeMounts:
    - name: custom-plugins
      mountPath: /usr/local/bin/go-wait
      subPath: go-wait

env:
  database: "off"
  nginx_worker_processes: "4"
  #proxy_access_log: /dev/stdout
  #admin_access_log: /dev/stdout
  #admin_gui_access_log: /dev/stdout
  #proxy_error_log: /dev/stderr
  #$admin_error_log: /dev/stderr
  #admin_gui_error_log: /dev/stderr
  #portal_api_error_log: /dev/stderr
  prefix: /kong_prefix/
  log_level: debug
  #PLUGINS: go-wait,response-transformer
  #pluginserver_names: go-wait
  #PLUGINSERVER_GO_WAIT_QUERY_CMD: /usr/local/bin/go-wait -dump
  ## the chart uses the traditional router (for Kong 3.x+) because the ingress
  ## controller generates traditional routes. if you do not use the controller,
  ## you may set this to "traditional_compatible" or "expression" to use the new
  ## DSL-based router

ingressController:
  installCRDs: false
  userDefinedVolumeMounts:
    - name: custom-plugins
      mountPath: /usr/local/bin/go-wait
      subPath: go-wait