deployment:
  userDefinedVolumes:
    - name: iam-plugins
      hostPath:
        path: /kong/iam-plugins

  userDefinedVolumeMounts:
    - name: iam-plugins
      mountPath: /usr/local/bin/iam-plugins
      subPath: iam-plugins
env:
  database: "off"
  nginx_worker_processes: "4"
  proxy_access_log: /dev/stdout
  admin_access_log: /dev/stdout
  admin_gui_access_log: /dev/stdout
  proxy_error_log: /dev/stderr
  #$admin_error_log: /dev/stderr
  #admin_gui_error_log: /dev/stderr
  portal_api_error_log: /dev/stderr
  prefix: /kong_prefix/
  log_level: debug
  PLUGINS: response-transformer,iam-plugins,cookies-to-headers

  pluginserver_names: iam-plugins
  #PLUGINSERVER_GO_WAIT_QUERY_CMD: /usr/local/bin/go-wait -dump
  PLUGINSERVER_IAM_PLUGINS_QUERY_CMD: /usr/local/bin/iam-plugins -dump

  ## the chart uses the traditional router (for Kong 3.x+) because the ingress
  ## controller generates traditional routes. if you do not use the controller,
  ## you may set this to "traditional_compatible" or "expression" to use the new
  ## DSL-based router

ingressController:
  installCRDs: false
  userDefinedVolumeMounts:
    - name: iam-plugins
      mountPath: /usr/local/bin/iam-plugins
      subPath: iam-plugins

plugins:
  configMaps:
    - pluginName: cookies-to-headers
      name: cookies-to-headers 