apiVersion: v1
kind: ConfigMap
metadata:
  name: cookies-to-headers
data:
  handler.lua: |2-

    -- handler.lua
    local kong = kong

    local CookieToHeaders = {
      PRIORITY = 1010,
      VERSION = "1.1-4",
    }

    function CookieToHeaders:access(plugin_conf)
      kong.response.set_header("fuck-kong-xxx", "fuck you kong")
    end

    return CookieToHeaders
  schema.lua: |-
    -- schema.lua
    local typedefs = require "kong.db.schema.typedefs"

    return {
        name = "cookies-to-headers",
        fields = {
            { consumer = typedefs.no_consumer },
            { protocols = typedefs.protocols_http },
            {
                config = {
                    type = "record",
                    fields = {},
                }
            },
        },
    }