apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
    - host: da.com 
      http:
        paths:
          - path: /policy
            pathType: ImplementationSpecific
            backend:
              service:
                name: echo
                port:
                  number: 80